//
//  Route.swift
//  ShootBuddy
//
//  Created by Gabriela Staňková on 13.06.2026.
//
import SwiftUI
import MapKit

/// Lifecycle of a route, derived from its dates (mirrors the `TripStatus`
/// pattern). Useful for sorting and colouring the Routes list.
enum RouteStatus {
    case planned     // hasn't started yet
    case inProgress  // happening right now
    case completed   // already finished

    var name: String {
        switch self {
            case .planned:
                return "Planned"
            case .inProgress:
                return "In Progress"
            case .completed:
                return "Completed"
        }
    }

    var color: Color {
        switch self {
            case .planned:
                return .blue
            case .inProgress:
                return .orange
            case .completed:
                return .green
        }
    }
}

/// One stop on a route: a spot, the light it is being shot in, and the time
/// block reserved for it. Shown as a timeline entry on the Route Detail screen.
///
/// `arrivalTime` and `departureTime` are produced by the generator from the
/// matching `LightWindow` and the active `ShootPreset` time block.
struct RouteStop: Identifiable {
    var id: UUID = UUID()

    /// The spot for this stop. Embedded as a value snapshot so the route keeps
    /// the plan as generated. (If you move to Core Data relationships you can
    /// swap this for a `spotID: UUID` reference instead.)
    var spot: Spot

    /// Which light this stop is planned for (one of `spot.lightConditions`).
    var assignedLight: LightType

    var arrivalTime: Date
    var departureTime: Date

    /// Optional per-stop direction, e.g. "Capture the first light breaking
    /// over the horizon." Defaults from the spot's note when generated.
    var note: String?

    /// True when this stop was auto-inserted to fill a gap rather than picked
    /// by the photographer.
    var isAutoGenerated: Bool = false
    
    /// Travel time in seconds from the previous stop to this one.
    /// Will be 0 for the first stop in the route.
    var travelTimeFromPrevious: TimeInterval = 0

    var location: CLLocation {
        CLLocation(latitude: spot.coordinate.latitude,
                   longitude: spot.coordinate.longitude)
    }
}

/// A photographer's plan for a single day: a time-ordered list of stops.
struct Route: Identifiable, Hashable {
    var id: UUID = UUID()
    var name: String

    /// Target number of spots requested on the New Route screen. The generator
    /// fills up to this many, auto-selecting spots for any remaining slots.
    var desiredSpotCount: Int

    /// Preferred/constraint start time entered by the user. The generator uses this
    /// as the earliest time to schedule stops. The actual route may start later
    /// (see `actualStartTime`).
    var startDate: Date
    
    /// Preferred/constraint end time entered by the user. The generator uses this
    /// as the latest time to schedule stops. The actual route may end earlier
    /// (see `actualEndTime`).
    var endDate: Date

    /// Time-ordered stops produced by the generator.
    var stops: [RouteStop]

    var note: String?
    
    /// Transport mode used for this route (driving or walking)
    var transportMode: TransportMode = .driving

    /// Identifier of the synced event in Apple Calendar, if the route was
    /// exported via EventKit ("sync to Apple calendar").
    var calendarEventID: String?

    // MARK: Derived
    
    // MARK: - Actual Route Times (computed from stops)
    
    /// The actual start time of the route (first stop's arrival time).
    /// Falls back to `startDate` if there are no stops yet.
    var actualStartTime: Date {
        stops.first?.arrivalTime ?? startDate
    }
    
    /// The actual end time of the route (last stop's departure time).
    /// Falls back to `endDate` if there are no stops yet.
    var actualEndTime: Date {
        stops.last?.departureTime ?? endDate
    }
    
    /// Total duration of the actual route in seconds (from first arrival to last departure).
    var actualDuration: TimeInterval {
        actualEndTime.timeIntervalSince(actualStartTime)
    }
    
    /// Total duration of the preferred time window in seconds (user's constraint).
    var preferredDuration: TimeInterval {
        endDate.timeIntervalSince(startDate)
    }

    var locationCount: Int { stops.count }

    /// Total travel distance in metres, summed across consecutive stops.
    var totalDistanceMeters: CLLocationDistance {
        guard stops.count > 1 else { return 0 }
        var total: CLLocationDistance = 0
        for index in 1..<stops.count {
            total += stops[index].location.distance(from: stops[index - 1].location)
        }
        return total
    }

    /// e.g. "13.4km total"
    var totalDistanceText: String {
        String(format: "%.1fkm total", totalDistanceMeters / 1000)
    }

    /// Route status based on actual route times (not the preferred time window).
    var status: RouteStatus {
        let now = Date()
        if now < actualStartTime {
            return .planned
        } else if now > actualEndTime {
            return .completed
        } else {
            return .inProgress
        }
    }
    
    // MARK: - Hashable
    
    func hash(into hasher: inout Hasher) {
        hasher.combine(id)
    }
    
    static func == (lhs: Route, rhs: Route) -> Bool {
        lhs.id == rhs.id
    }
}


//MARK - marek notifikace
extension Route {
    // Returns the route stop that is active right now, based on arrival and departure time.ti 
    var currentStop: RouteStop? {
        let now = Date()

        guard status == .inProgress else {
            return nil
        }

        return stops.first { stop in
            now >= stop.arrivalTime && now <= stop.departureTime
        }
    }
}
