//
//  AddSpotToRouteViewModel.swift
//  ShootBuddy
//
//  Created by Gabriela Staňková on 17.06.2026.
//

import SwiftUI

@Observable
class AddSpotToRouteViewModel {
    var state: AddSpotToRouteViewState
    
    private var dataManager: DataManaging
    private var routeGenerator: RouteGenerating
    
    init(spot: Spot) {
        self.state = AddSpotToRouteViewState(spot: spot)
        self.dataManager = DIContainer.shared.resolve()
        self.routeGenerator = DIContainer.shared.resolve()
    }
    
    func loadRoutes() {
        state.isLoading = true
        
        // Fetch all routes and sort by date (upcoming first)
        state.routes = dataManager.fetchRoutes()
            .sorted { $0.startDate < $1.startDate }
        
        state.isLoading = false
    }
    
    func addSpotToRoute(_ route: Route) async {
        print("🔄 Adding spot '\(state.spot.name)' to route '\(route.name)'")
        state.isLoading = true
        
        // Collect all spots that should be in the route:
        // - Existing user-selected spots (non-auto-generated)
        // - The new spot being added
        let existingUserSpots = route.stops
            .filter { !$0.isAutoGenerated }
            .map { $0.spot }
        
        var selectedSpots = existingUserSpots
        var isNewSpot = false
        
        // Add the new spot if it's not already in the route
        if !selectedSpots.contains(where: { $0.id == state.spot.id }) {
            selectedSpots.append(state.spot)
            isNewSpot = true
        }
        
        print("📍 Regenerating route with \(selectedSpots.count) user-selected spots")
        
        // Get all available spots for potential auto-fill
        let allAvailableSpots = dataManager.fetchSpots()
        
        // Determine the base location (use first stop's location or the new spot's location)
        let baseLocation = route.stops.first?.spot.coordinate ?? state.spot.coordinate
        
        // Calculate new desired spot count
        // If adding a new spot, increase the desired count by 1
        let newDesiredSpotCount = isNewSpot ? route.desiredSpotCount + 1 : route.desiredSpotCount
        
        print("🎯 Desired spot count: \(route.desiredSpotCount) → \(newDesiredSpotCount)")
        
        // Regenerate the route with the route generator
        let newStops = await routeGenerator.generateRoute(
            selectedSpots: selectedSpots,
            date: route.startDate,
            startTime: route.startDate,
            endTime: route.endDate,
            desiredSpotCount: newDesiredSpotCount,
            baseLocation: baseLocation,
            allAvailableSpots: allAvailableSpots,
            transportMode: route.transportMode
        )
        
        // Create updated route with new stops and updated desired count
        var updatedRoute = route
        updatedRoute.stops = newStops
        updatedRoute.desiredSpotCount = newDesiredSpotCount
        
        // Save the updated route
        dataManager.saveRoute(updatedRoute)
        
        state.isLoading = false
        
        print("✅ Route regenerated with \(newStops.count) stops (optimized placement and travel times)")
        print("✅ Desired spot count updated to \(newDesiredSpotCount)")
    }
}
