//
//  RouteGapFiller.swift
//  ShootBuddy
//
//  Created by Gabriela Staňková on 17.06.2026.
//

import Foundation
import CoreLocation
import MapKit

/// Handles filling gaps in routes with additional spots
struct RouteGapFiller {
    private let travelTimeCache: TravelTimeCache
    private let shootDuration: TimeInterval
    
    init(travelTimeCache: TravelTimeCache, shootDuration: TimeInterval) {
        self.travelTimeCache = travelTimeCache
        self.shootDuration = shootDuration
    }
    
    /// Fills gaps in the route with nearby spots that match the light conditions
    func fillGapsWithNearbySpots(
        currentStops: [RouteStop],
        lightWindows: [LightWindow],
        availableSpots: [Spot],
        targetCount: Int,
        startTime: Date,
        endTime: Date,
        baseLocation: CLLocationCoordinate2D
    ) async -> [RouteStop] {
        var allStops = currentStops
        var usedSpotIDs = Set(currentStops.map { $0.spot.id })
        
        guard !availableSpots.isEmpty else {
            print("  ℹ️ No available spots for gap filling")
            return allStops
        }
        
        print("  🔄 Starting iterative gap filling (current: \(allStops.count), target: \(targetCount))")
        
        // Keep filling gaps until we reach target count
        while allStops.count < targetCount {
            let unusedSpots = availableSpots.filter { !usedSpotIDs.contains($0.id) }
            
            guard !unusedSpots.isEmpty else {
                print("  ℹ️ Ran out of unused spots (filled \(allStops.count)/\(targetCount))")
                break
            }
            
            // Find gaps in current schedule
            let gaps = findGaps(in: allStops, startTime: startTime, endTime: endTime)
            
            guard !gaps.isEmpty else {
                print("  ℹ️ No more gaps available")
                break
            }
            
            var filledThisIteration = false
            
            // Try to fill each gap
            for gap in gaps {
                if allStops.count >= targetCount {
                    break
                }
                
                // Find all light windows that overlap with this gap
                let overlappingWindows = lightWindows.filter { window in
                    gap.start < window.end && gap.end > window.start
                }
                
                if !overlappingWindows.isEmpty {
                    print("  🔍 Gap \(formatTime(gap.start))-\(formatTime(gap.end)) overlaps with: \(overlappingWindows.map { $0.lightType.name }.joined(separator: ", "))")
                }
                
                guard !overlappingWindows.isEmpty else {
                    continue
                }
                
                // Try each overlapping window until we find a spot
                for lightWindow in overlappingWindows {
                    if allStops.count >= targetCount {
                        break
                    }
                    
                    // Find spots that match this light condition and aren't used yet
                    let matchingSpots = unusedSpots.filter { spot in
                        spot.lightConditions.contains(lightWindow.lightType) &&
                        !usedSpotIDs.contains(spot.id)
                    }
                    
                    guard !matchingSpots.isEmpty else {
                        continue
                    }
                    
                    // Find the closest spot to the gap location (or baseLocation if no reference)
                    let gapLocation = gap.referenceLocation ?? baseLocation
                    let closestSpot = await findClosestSpot(
                        to: gapLocation,
                        from: matchingSpots,
                        maxDistance: 50000 // 50km max
                    )
                    
                    guard let spot = closestSpot else {
                        continue
                    }
                    
                    // Calculate when to schedule this spot within the overlapping time
                    let scheduleStart = max(gap.start, lightWindow.start)
                    let scheduleEnd = min(gap.end, lightWindow.end)
                    
                    // Check if we can fit this spot in the overlapping time
                    if scheduleEnd.timeIntervalSince(scheduleStart) >= shootDuration {
                        let stop = RouteStop(
                            spot: spot,
                            assignedLight: lightWindow.lightType,
                            arrivalTime: scheduleStart,
                            departureTime: scheduleStart.addingTimeInterval(shootDuration),
                            note: spot.note,
                            isAutoGenerated: true
                        )
                        
                        allStops.append(stop)
                        usedSpotIDs.insert(spot.id)
                        filledThisIteration = true
                        
                        print("  🤖 Filled gap with: \(spot.name) at \(formatTime(scheduleStart)) (\(lightWindow.lightType.name)) [Total: \(allStops.count)/\(targetCount)]")
                        break // Move to next gap
                    }
                }
            }
            
            // If we couldn't fill any gaps this iteration, break to avoid infinite loop
            if !filledThisIteration {
                print("  ⚠️ Could not fill any more gaps (reached \(allStops.count)/\(targetCount))")
                break
            }
        }
        
        print("  ✅ Gap filling complete: \(allStops.count) stops")
        return allStops
    }
    
    /// Finds gaps in the schedule where we could add more spots
    func findGaps(in stops: [RouteStop], startTime: Date, endTime: Date) -> [Gap] {
        guard !stops.isEmpty else {
            return [Gap(start: startTime, end: endTime, duration: endTime.timeIntervalSince(startTime), referenceLocation: nil)]
        }
        
        var gaps: [Gap] = []
        let sortedStops = stops.sorted { $0.arrivalTime < $1.arrivalTime }
        
        // Gap before first stop
        if sortedStops.first!.arrivalTime > startTime {
            let duration = sortedStops.first!.arrivalTime.timeIntervalSince(startTime)
            if duration >= shootDuration {
                gaps.append(Gap(
                    start: startTime,
                    end: sortedStops.first!.arrivalTime,
                    duration: duration,
                    referenceLocation: sortedStops.first!.spot.coordinate
                ))
            }
        }
        
        // Gaps between stops
        for i in 0..<sortedStops.count - 1 {
            let currentStop = sortedStops[i]
            let nextStop = sortedStops[i + 1]
            
            let gapStart = currentStop.departureTime
            let gapEnd = nextStop.arrivalTime
            let duration = gapEnd.timeIntervalSince(gapStart)
            
            if duration >= shootDuration {
                // Use midpoint between two stops as reference
                let midLat = (currentStop.spot.coordinate.latitude + nextStop.spot.coordinate.latitude) / 2
                let midLon = (currentStop.spot.coordinate.longitude + nextStop.spot.coordinate.longitude) / 2
                
                gaps.append(Gap(
                    start: gapStart,
                    end: gapEnd,
                    duration: duration,
                    referenceLocation: CLLocationCoordinate2D(latitude: midLat, longitude: midLon)
                ))
            }
        }
        
        // Gap after last stop
        if sortedStops.last!.departureTime < endTime {
            let duration = endTime.timeIntervalSince(sortedStops.last!.departureTime)
            if duration >= shootDuration {
                gaps.append(Gap(
                    start: sortedStops.last!.departureTime,
                    end: endTime,
                    duration: duration,
                    referenceLocation: sortedStops.last!.spot.coordinate
                ))
            }
        }
        
        return gaps
    }
    
    /// Finds the closest spot to a given location
    func findClosestSpot(
        to location: CLLocationCoordinate2D,
        from spots: [Spot],
        maxDistance: Double
    ) async -> Spot? {
        var closestSpot: Spot?
        var shortestDistance: Double = maxDistance
        
        for spot in spots {
            let distance = MKMapPoint(location).distance(to: MKMapPoint(spot.coordinate))
            
            if distance < shortestDistance {
                shortestDistance = distance
                closestSpot = spot
            }
        }
        
        return closestSpot
    }
    
    private func formatTime(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.timeStyle = .short
        return formatter.string(from: date)
    }
}
